### PR TITLE
Relocate Create new wallet functionality

### LINKED ISSUE #402: Relocate Create new Wallet functionality

### PR DESCRIPTION
**Pull request by d-novak**
Closes #402 

Relocated the `Create New Wallet` functionality from the navigation to the Mnemonic login page.

### CODE REVIEW

**Comment by refi93** [comment]
please remove `isLeftClick` require from `navbarUnauth.js` since it's unused now

**Comment by d-novak** [comment]
@refi93 Sorry missed that, removed

**Comment by refi93** [comment]
after discussing it with Michal we came to the conclusion that it would be better to have both the "create new wallet" button on the navbar and in the mnemonic tab. The reason is that without the button the landing page would lack any call to action.

**Comment by d-novak** [comment]
@refi93 Added it back

**Pull request merged**
